"""bring back movies table

Revision ID: 0ec6a7bf89e9
Revises: 
Create Date: 2025-11-12 00:30:58.295156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '0ec6a7bf89e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if table already exists (for cases where DB was created outside Alembic)
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'movies' not in tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('movies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('genre', sa.String(length=100), nullable=True),
        sa.Column('director', sa.String(length=255), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('is_imax', sa.Boolean(), nullable=True),
        sa.Column('poster_url', sa.String(length=255), nullable=True),
        sa.Column('trailer_url', sa.String(length=255), nullable=True),
        sa.Column('cast', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    
    # Check and create foreign keys if they don't exist
    if 'bookings' in tables:
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('bookings')]
        # Check if foreign key to movies already exists
        bookings_fks = inspector.get_foreign_keys('bookings')
        has_movie_fk = any(
            fk['referred_table'] == 'movies' and 'movie_id' in fk['constrained_columns']
            for fk in bookings_fks
        )
        if not has_movie_fk:
            op.create_foreign_key('fk_bookings_movie_id', 'bookings', 'movies', ['movie_id'], ['id'])
    
    if 'showings' in tables:
        showings_fks = inspector.get_foreign_keys('showings')
        has_movie_fk = any(
            fk['referred_table'] == 'movies' and 'movie_id' in fk['constrained_columns']
            for fk in showings_fks
        )
        if not has_movie_fk:
            op.create_foreign_key('fk_showings_movie_id', 'showings', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'showings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
